version: '2'

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: 'developmentseed/geolambda-base:latest'
    entrypoint: /bin/bash

  core:
    build:
      context: .
    image: 'developmentseed/geolambda:latest'
    entrypoint: /bin/bash
    links:
      - base

  test-python27:
    build:
      context: .
      dockerfile: Dockerfile.test-python27
    image: developmentseed/geolambda:test-python27
    entrypoint: /bin/bash

  test-python36:
    build:
      context: .
      dockerfile: Dockerfile.test-python36
    image: developmentseed/geolambda:test-python26
    entrypoint: /bin/bash

#  runner:
#    build:
#      context: .
#      dockerfile: Dockerfile.runner
#    image: 'developmentseed/geolamnda:runner'
#    links:
#      - base
